// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hthrsrekzyobmlvtquub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0aHJzcmVrenlvYm1sdnRxdXViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5Mzc5MzMsImV4cCI6MjA2MzUxMzkzM30.V4ZIY4I1R3tUIWkuEU7t0ExC8gbLJKYjIPvrERbdbIw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);