name: Lint and License Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  eslint:
    name: ESLint (Frontend)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
        
      - name: Run ESLint
        run: npm run lint
  
  typescript-check:
    name: TypeScript Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
        
      - name: TypeScript check frontend
        run: npx tsc --noEmit
        
      - name: TypeScript check backend
        working-directory: ./server
        run: |
          npm ci
          npx tsc --noEmit
  
  python-lint:
    name: Python Lint (Bot Chain)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort
      
      - name: Check Python files exist
        run: |
          if find bot_chain -name "*.py" | grep -q .; then
            echo "Python files found"
          else
            echo "No Python files found in bot_chain, skipping lint"
            exit 0
          fi
      
      - name: Run flake8
        run: find bot_chain -name "*.py" -exec flake8 {} + || true
        
      - name: Check Black formatting
        run: find bot_chain -name "*.py" -exec black --check {} + || true
        
      - name: Check import sorting
        run: find bot_chain -name "*.py" -exec isort --check-only {} + || true
  
  license-check:
    name: License Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Check for LICENSE file
        run: |
          if [ -f LICENSE ]; then
            echo "✓ LICENSE file exists"
          else
            echo "⚠️ WARNING: No LICENSE file found"
            echo "Creating MIT LICENSE file..."
            cat > LICENSE << 'EOF'
          MIT License

          Copyright (c) 2025 CECI-AI Team

          Permission is hereby granted, free of charge, to any person obtaining a copy
          of this software and associated documentation files (the "Software"), to deal
          in the Software without restriction, including without limitation the rights
          to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
          copies of the Software, and to permit persons to whom the Software is
          furnished to do so, subject to the following conditions:

          The above copyright notice and this permission notice shall be included in all
          copies or substantial portions of the Software.

          THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
          IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
          FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
          AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
          LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
          OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
          SOFTWARE.
          EOF
          fi
      
      - name: Verify package.json license field
        run: |
          if grep -q '"license":' package.json; then
            echo "✓ License field found in package.json"
          else
            echo "⚠️ WARNING: No license field in package.json"
          fi